import os
import yaml


# Load configuration
configfile: "config/config.yaml"


# Include common functions and rule files
include: "rules/common.smk"
include: "rules/data_preparation.smk"
include: "rules/download_extract.smk"
include: "rules/seqfu.smk"
include: "rules/seqkit.smk"
include: "rules/quast.smk"


rule all:
    input:
        # Genome download and assembly statistics
        "resources/genomes/.download_complete",
        "results/qc/.stats_complete",
        # QUAST quality assessment
        "results/qc/quast/.quast_complete",
