import os
import yaml


# Load configuration
configfile: "config/config.yaml"


# Include common functions and rule files
include: "rules/common.smk"
include: "rules/data_preparation.smk"
include: "rules/download_extract.smk"
include: "rules/seqfu.smk"
include: "rules/seqkit.smk"
include: "rules/blast.smk"
include: "rules/analysis.smk"


# include: "rules/plantismash.smk"


rule all:
    input:
        "results/analysis_summary.txt",
        #"resources/plantismash_databases/.download_done",
        #*(
        #    [
        #        "results/plantismash_coverage_analysis.csv",
        #        "results/plantismash_coverage_stats.txt",
        #    ]
        #    if config.get("run_coverage_analysis", True)
        #    else []
        #),
